(() => {
  const cfg = SMARTFARM; const key = 'smartfarm.sensor.history.v1'; let client; let rangeHours = 24;
  const $ = id => document.getElementById(id); const load = () => { try { return JSON.parse(localStorage.getItem(key) || '[]').filter(x => Number.isFinite(x.t)); } catch (_) { return []; } }; let points = load();
  const save = () => localStorage.setItem(key, JSON.stringify(points.slice(-5000)));
  function niceNumber(n, suffix) { return Number.isFinite(n) ? `${n.toFixed(suffix === '°C' ? 1 : 0)}${suffix}` : `--${suffix}`; }
  function draw(canvas, values, color, fill) { const ctx = canvas.getContext('2d'), w = canvas.width = canvas.clientWidth * devicePixelRatio, h = canvas.height = canvas.clientHeight * devicePixelRatio; ctx.scale(devicePixelRatio, devicePixelRatio); const W = canvas.clientWidth, H = canvas.clientHeight; ctx.clearRect(0,0,W,H); if (values.length < 2) return false; const nums = values.map(x => x.v), min = Math.min(...nums), max = Math.max(...nums), pad = Math.max((max-min)*.18, .5); const y = n => H-18-((n-(min-pad))/(max-min+pad*2))*(H-34), x = i => 12+(i/(values.length-1))*(W-24); ctx.strokeStyle='#ffffff12';ctx.lineWidth=1; for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(0,i*H/4);ctx.lineTo(W,i*H/4);ctx.stroke()} ctx.beginPath(); values.forEach((p,i)=>{const px=x(i),py=y(p.v);i?ctx.lineTo(px,py):ctx.moveTo(px,py)}); ctx.lineWidth=2.5;ctx.strokeStyle=color;ctx.stroke();ctx.lineTo(W-12,H-18);ctx.lineTo(12,H-18);ctx.closePath();const gradient=ctx.createLinearGradient(0,0,0,H);gradient.addColorStop(0,fill);gradient.addColorStop(1,'transparent');ctx.fillStyle=gradient;ctx.fill(); const last=values.at(-1);ctx.beginPath();ctx.arc(x(values.length-1),y(last.v),4,0,Math.PI*2);ctx.fillStyle=color;ctx.fill(); return true; }
  function render() { const cutoff=Date.now()-rangeHours*3600000, selected=points.filter(p=>p.t>=cutoff), temps=selected.map(p=>({v:p.temp,t:p.t})).filter(p=>Number.isFinite(p.v)), hums=selected.map(p=>({v:p.hum,t:p.t})).filter(p=>Number.isFinite(p.v)); const last=points.at(-1); $('tempCurrent').textContent=niceNumber(last?.temp,'°C'); $('humCurrent').textContent=niceNumber(last?.hum,'%'); $('pointCount').textContent=selected.length; $('lastSync').textContent=last?new Date(last.t).toLocaleString('th-TH'):'--'; $('tempEmpty').style.display=draw($('tempChart'),temps,'#d6b36a','#d6b36a44')?'none':'grid'; $('humEmpty').style.display=draw($('humChart'),hums,'#7aa8ff','#7aa8ff44')?'none':'grid'; }
  function connect() { const username=$('mqttUser').value.trim(),password=$('mqttPass').value;if(!username||!password)return;client?.end(true);client=mqtt.connect(cfg.broker,{username,password,clientId:`SmartFarmAnalytics-${Math.random().toString(16).slice(2)}`,reconnectPeriod:3000});client.on('connect',()=>{$('mqttStatus').textContent='MQTT เชื่อมต่อแล้ว';client.subscribe(`${cfg.base}/sensor/dht11`);});client.on('close',()=>{$('mqttStatus').textContent='การเชื่อมต่อขาดหาย'});client.on('message',(topic,raw)=>{if(topic!==`${cfg.base}/sensor/dht11`)return;try{const d=JSON.parse(raw.toString()),temp=Number(d.temperature),hum=Number(d.humidity);if(!Number.isFinite(temp)||!Number.isFinite(hum))return;points.push({t:Date.now(),temp,hum});points=points.slice(-5000);save();render();}catch(_){}}); }
  $('connectBtn').onclick=connect; document.querySelectorAll('[data-range]').forEach(btn=>btn.onclick=()=>{rangeHours=Number(btn.dataset.range);document.querySelectorAll('[data-range]').forEach(x=>x.classList.toggle('active',x===btn));render()}); $('clearHistory').onclick=()=>{if(confirm('ล้างประวัติเซ็นเซอร์ในเครื่องนี้หรือไม่?')){points=[];save();render()}}; window.addEventListener('resize',render); render();
})();
