[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient
  tzapu/WiFiManager
  arduino-libraries/NTPClient
  adafruit/RTClib
  adafruit/DHT sensor library
  bblanchon/ArduinoJson
  ayushsharma82/ElegantOTA
