(() => {
  const key='smartfarm.sensor.history.v1', $=id=>document.getElementById(id); let period='day';
  const load=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]').filter(x=>Number.isFinite(x.t))}catch(_){return[]}};
  const pad=n=>String(n).padStart(2,'0'); const dateKey=(t,monthly=false)=>{const d=new Date(t);return monthly?`${d.getFullYear()}-${pad(d.getMonth()+1)}`:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
  const today=new Date(); $('periodInput').value=`${today.getFullYear()}-${pad(today.getMonth()+1)}-${period==='day'?pad(today.getDate()):''}`.replace(/-$/,'');
  function summarize(){const input=$('periodInput').value||dateKey(Date.now(),period==='month'), data=load().filter(x=>dateKey(x.t,period==='month')===input), temps=data.map(x=>Number(x.temp)).filter(Number.isFinite), hums=data.map(x=>Number(x.hum)).filter(Number.isFinite); const avg=a=>a.length?a.reduce((s,n)=>s+n,0)/a.length:null; const avgt=avg(temps),avgh=avg(hums); $('avgTemp').textContent=avgt==null?'--°C':`${avgt.toFixed(1)}°C`; $('avgHum').textContent=avgh==null?'--%':`${avgh.toFixed(0)}%`; $('tempRange').textContent=temps.length?`ต่ำสุด ${Math.min(...temps).toFixed(1)} · สูงสุด ${Math.max(...temps).toFixed(1)}`:'ต่ำสุด -- · สูงสุด --'; $('humRange').textContent=hums.length?`ต่ำสุด ${Math.min(...hums).toFixed(0)} · สูงสุด ${Math.max(...hums).toFixed(0)}`:'ต่ำสุด -- · สูงสุด --'; $('samples').textContent=data.length.toLocaleString('th-TH'); $('health').textContent=avgt==null?'--':(avgt>=20&&avgt<=35&&avgh>=40&&avgh<=85?'ปกติ':'ตรวจสอบ'); $('reportPeriod').textContent=period==='month'?`เดือน ${input}`:`วันที่ ${input}`; drawBars('tempBars',aggregate(data,'temp'), '#d6b36a','°C'); drawBars('humBars',aggregate(data,'hum'), '#7aa8ff','%'); }
  function aggregate(data,field){const map={};data.forEach(x=>{const k=period==='day'?new Date(x.t).getHours():new Date(x.t).getDate();(map[k]??=[]).push(Number(x[field]))});return Object.entries(map).map(([k,a])=>({key:k,value:a.reduce((s,n)=>s+n,0)/a.length})).sort((a,b)=>Number(a.key)-Number(b.key))}
  function drawBars(id,data,color,suffix){const host=$(id);host.innerHTML='';if(!data.length){host.innerHTML='<div class="report-empty">ยังไม่มีข้อมูลในช่วงเวลานี้</div>';return}const max=Math.max(...data.map(x=>x.value)),min=Math.min(...data.map(x=>x.value)),span=Math.max(max-min,1);data.forEach(x=>{const h=28+((x.value-min)/span)*52,bar=document.createElement('div');bar.className='bar-column';bar.innerHTML=`<div class="bar-value">${x.value.toFixed(suffix==='°C'?1:0)}</div><div class="bar" style="height:${h}%;background:${color}"></div><small>${period==='day'?pad(x.key)+':00':x.key}</small>`;host.appendChild(bar)})}
  function csv(){const input=$('periodInput').value,data=load().filter(x=>dateKey(x.t,period==='month')===input),rows=[['timestamp','temperature_c','humidity_percent'],...data.map(x=>[new Date(x.t).toISOString(),x.temp,x.hum])];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`smartfarm-${period}-${input}.csv`;a.click();URL.revokeObjectURL(a.href)}
  document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));const d=new Date();$('periodInput').type=period==='day'?'date':'month';$('periodInput').value=period==='day'?dateKey(Date.now()):dateKey(Date.now(),true);summarize()});$('periodInput').onchange=summarize;$('exportReport').onclick=csv;summarize();
})();
