(() => {
  const c = SMARTFARM; let client;
  const $ = id => document.getElementById(id);
  const log = text => { $('log').textContent = `${new Date().toLocaleTimeString('th-TH')}  ${text}`; };
  const labels = { ...c.defaults };
  function render() {
    $('timers').innerHTML = c.relays.map((r, i) => `<div class="rule-row"><div><b>รีเลย์ ${i + 1} · ${labels[r]}</b><small>เปิดทันที แล้วปิดอัตโนมัติ</small></div><div class="rule-actions"><input type="number" min="1" max="71582" value="30" data-minutes="${r}" aria-label="จำนวนนาที ${labels[r]}"><span class="unit">นาที</span><button class="gold-button" data-timer="${r}">เริ่ม Timer</button><button class="muted-button" data-cancel="${r}">ยกเลิก</button></div></div>`).join('');
    $('schedules').innerHTML = c.relays.map((r, i) => `<div class="rule-row schedule-row"><div><b>รีเลย์ ${i + 1} · ${labels[r]}</b><small>ทำงานทุกวัน · บันทึกลง ESP8266</small></div><div class="schedule-fields"><label>เปิด<input type="time" data-on="${r}" value="06:00"></label><label>ปิด<input type="time" data-off="${r}" value="06:20"></label><label class="switch-label"><input type="checkbox" data-enabled="${r}" checked><span>ใช้งาน</span></label></div></div>`).join('');
    document.querySelectorAll('[data-timer]').forEach(button => button.onclick = () => { const mins = Number(document.querySelector(`[data-minutes="${button.dataset.timer}"]`).value); if (!Number.isInteger(mins) || mins < 1 || mins > 71582) return log('Timer ต้องอยู่ระหว่าง 1–71,582 นาที'); publish(`${c.base}/relay/${button.dataset.timer}/timer/set`, String(mins * 60)); });
    document.querySelectorAll('[data-cancel]').forEach(button => button.onclick = () => publish(`${c.base}/relay/${button.dataset.cancel}/timer/set`, 'CANCEL'));
  }
  function publish(topic, payload) { if (window.FIREBASE_AUTH_ENABLED && !window.SmartFarmAccess?.can("operator")) return log("ไม่มีสิทธิ์ตั้งค่าอัตโนมัติ"); if (!client?.connected) return log('กรุณาเชื่อมต่อ MQTT ก่อน'); client.publish(topic, payload, { qos: 1, retain: false }); log(`ส่งคำสั่ง ${payload} สำเร็จ`); }
  $('connectBtn').onclick = () => { const username = $('mqttUser').value.trim(), password = $('mqttPass').value; if (!username || !password) return log('กรุณากรอก MQTT username และ password'); client?.end(true); client = mqtt.connect(c.broker, { username, password, clientId: `SmartFarmAutomation-${Math.random().toString(16).slice(2)}`, reconnectPeriod: 3000 }); client.on('connect', () => { $('status').textContent = 'MQTT เชื่อมต่อแล้ว'; client.subscribe(`${c.base}/#`); log('เชื่อมต่อศูนย์ควบคุมสำเร็จ'); }); client.on('close', () => { $('status').textContent = 'การเชื่อมต่อขาดหาย'; }); client.on('error', error => log(`MQTT error: ${error.message}`)); };
  $('saveAll').onclick = () => { if (!client?.connected) return log('กรุณาเชื่อมต่อ MQTT ก่อน'); c.relays.forEach(r => { const on = document.querySelector(`[data-on="${r}"]`).value, off = document.querySelector(`[data-off="${r}"]`).value, enabled = document.querySelector(`[data-enabled="${r}"]`).checked; const payload = enabled ? { slots: [{ enabled: true, on, off }] } : { slots: [{ enabled: false, on: '00:00', off: '00:00' }] }; publish(`${c.base}/schedule/${r}/set`, JSON.stringify(payload)); }); log('บันทึก Schedule ทั้งหมดแล้ว'); };
  render();
})();
